version: "3.7"
services:
  app:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    volumes:
      - ../:/usr/local/gv-ccb
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./local-php.ini:/etc/php7/conf.d/local-php.ini
    working_dir: /usr/local/gv-ccb
    ports:
      - "80:80"
      - "9000:9000"
