name: Build

on:
  pull_request:
    branches:
      - production

env:
  IMAGE_NAME: "lumen-actions-sandbox"
  CONTAINER_REPO: "gcr.io/lithe-breaker-191614"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          php-version: '7.4'
          tools: pecl
      - name: Environment
        run: |
          echo github.event: ${{ github.event }}
          echo github.run_number: ${{ github.run_number }}
          echo github.actor: ${{ github.actor }}
          echo github.event_name: ${{ github.event_name }}
          echo github.sha: ${{ github.sha }}
          echo github.ref: ${{ github.ref }}
          echo github.head_ref: ${{ github.head_ref }}
          echo github.base_ref: ${{ github.base_ref }}
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer install --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Directory Permissions
        run: mkdir -p storage bootstrap/cache && chmod -R 777 storage bootstrap/cache
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: vendor/bin/phpunit
      - name: Build the Docker image
        run: |
          php artisan version >.version
          docker build . --file docker/Dockerfile --tag "$IMAGE_NAME":$(date +%s) --tag "$CONTAINER_REPO"/"$IMAGE_NAME":"$GITHUB_SHA"

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_email: ${{ secrets.GCP_EMAIL }}
          service_account_key: ${{ secrets.GCP_KEY }}
      # Configure docker to use the gcloud command-line tool as a credential helper
      - run: |
          # Set up docker to authenticate
          # via gcloud command-line tool.
          gcloud auth configure-docker
      # Push the Docker image to Google Container Registry
      - name: Publish
        run: docker push "$CONTAINER_REPO"/"$IMAGE_NAME":"$GITHUB_SHA"

  deploy-staging:
    - uses: actions/checkout@v2
      with:
        php-version: '7.4'
        tools: pecl
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        service_account_email: ${{ secrets.GCP_EMAIL }}
        service_account_key: ${{ secrets.GCP_KEY }}
      # Deploy image to Cloud Run
      - name: Deploy Staging
        run: |-
          gcloud run deploy "$IMAGE_NAME" \
            --region us-central1 \
            --image "$CONTAINER_REPO"/$IMAGE_NAME:$GITHUB_SHA" \
            --platform "managed" \
            --allow-unauthenticated