name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          php-version: '7.4'
          tools: pecl
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer install --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Directory Permissions
        run: mkdir -p storage bootstrap/cache && chmod -R 777 storage bootstrap/cache
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: vendor/bin/phpunit
      - name: Build the Docker image
        run: docker build . --file docker/Dockerfile --tag groupvitals-ccb:$(date +%s)

  staging:
    needs: build
    name: Deploy to Staging
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          php-version: '7.4'
          tools: pecl
      # Setup gcloud CLI
#      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
#        with:
#          version: '270.0.0'
#          service_account_email: ${{ secrets.GKE_EMAIL }}
#          service_account_key: ${{ secrets.GKE_KEY }}
      - name: Deploy to Staging
        run: echo "Deploying to staging..."
