name: Laravel

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Directory Permissions
        run: mkdir -p storage bootstrap/cache && chmod -R 777 storage bootstrap/cache

  test:
    - needs: build
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: vendor/sbin/phpunit

  assemble:
    - needs: test
    - name: Build the Docker image
      run: docker build . --file docker/Dockerfile --tag groupvitals-ccb:$(date +%s)

  deploy-staging:
    - needs: assemble
    - name: Deploy to Staging
      run: echo "Deploying to staging..."
